import json
import os
import re
import random
from pathlib import Path


# ===== НАСТРОЙКИ =====
STATS_JSON_PATH = "../Files/Status/status_stats.json"
EFFECTS_JSON_PATH = "../Files/Status/status_effects.json"
OUTPUT_DIR = "../Scripts/Logic/Fight/StatusEffects/Gen"

BASE_CLASS = "StatusEffectBase"

# Путь к StatusEffectGenerator.gd относительно папки CodeGen
GENERATOR_PATH = "../Scripts/Logic/Fight/StatusEffects/StatusEffectGenerator.gd"


# ===== ВСПОМОГАТЕЛЬНЫЕ =====

def extract_template_variables(text: str) -> set[str]:
    return set(re.findall(r"{([\w.]+)}", text))

def snake_to_pascal(name: str) -> str:
    return ''.join(word.capitalize() for word in name.split('_'))

def pascal_to_snake(name: str) -> str:
    return re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()

def snake_to_upper(name: str) -> str:
    return name.upper()


def gdscript_value(value):
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, list):
        items = ", ".join(gdscript_value(v) for v in value)
        return f"[{items}]"
    return str(value)


def get_gdscript_type(value):
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, str):
        return "String"
    if isinstance(value, list):
        return "Array"
    return "Variant"


def generate_color_from_name(name: str) -> str:
    """Генерирует предсказуемый цвет на основе имени эффекта."""
    random.seed(name)
    r = round(random.uniform(0.2, 1.0), 3)
    g = round(random.uniform(0.2, 1.0), 3)
    b = round(random.uniform(0.2, 1.0), 3)
    return f"Color({r}, {g}, {b}, 1.0)"


# ===== ГЕНЕРАЦИЯ ФАЙЛА ЭФФЕКТА =====

def generate_const_block(config: dict) -> list[str]:
    """Генерирует строки с константами из конфига."""
    lines = ["# constants from config"]
    for key, value in config.items():
        if key in ["lore_name", "description"]:
            continue
        gd_type = get_gdscript_type(value)
        lines.append(
            f"const {key} : {gd_type} = {gdscript_value(value)}"
        )
    return lines


def generate_init_block(effect_name: str, config: dict) -> list[str]:
    """Генерирует содержимое _init()."""
    lines = []
    lore_name = config.get("lore_name", effect_name)
    description = config.get("description", "")

    lines.append(
        f"func _init(duration : int = default_duration) -> void:"
    )
    lines.append(f'\tlore_name = "{lore_name}"')
    lines.append(
        f'\tlore_description_template = "{description}"'
    )
    lines.append(
        f"\ttype = StatusGenerator.STATUS.{snake_to_upper(effect_name)}"
    )

    if "damage_type" in config:
        lines.append("\t_damage_type = ActionBase.DAMAGE_TYPE[damage_type]")
    lines.append("\tsuper(duration)")
    lines.append("")
    return lines


def get_description_block(effect_name: str, config: dict) -> list[str]:
    """Генерирует содержимое get_description()."""
    description = config.get("description", "")
    lines = []
    lines.append("func get_description() -> String:")
    lines.append("\tvar format_dict : Dictionary = {}")

    used_variables = extract_template_variables(description)

    for key in used_variables:
        lines.append(f'\tformat_dict["{key}"] = {key}')

    lines.append("")
    lines.append(
        "\treturn lore_description_template.format(format_dict)"
    )
    lines.append("")
    return lines


def generate_full_file(effect_name: str, config: dict) -> tuple[str, str]:
    """Генерирует полный файл с нуля (если его ещё нет)."""
    class_name = f"StatusEffect{snake_to_pascal(effect_name)}"

    lines = []
    lines.append("# This file is autogenerated")
    lines.append("")
    lines.append(f"class_name {class_name}")
    lines.append(f"extends {BASE_CLASS}")
    lines.append("")

    lines.extend(generate_const_block(config))
    lines.append("")
    lines.extend(generate_init_block(effect_name, config))
    lines.append("")

    lines.extend(get_description_block(effect_name, config))

    # on_turn_end
    lines.append(
        "func on_turn_end(actor : ActorBase, data = null) -> void:"
    )

    if "damage" in config:
        lines.append(
            "\tactor.take_damage(damage, _damage_type)"
        )

    lines.append("\tduration -= 1")
    lines.append("")

    # on_turn_start
    lines.append(
        "func on_turn_start(actor : ActorBase, data = null) -> void:"
    )
    lines.append("\tpass")
    lines.append("")

    return "\n".join(lines), class_name


def update_existing_file(file_path: Path, effect_name: str, config: dict) -> str:
    """Обновляет существующий файл: заменяет константы, _init() и get_description(), остальное оставляет."""
    content = file_path.read_text(encoding="utf-8")

    class_name = f"StatusEffect{snake_to_pascal(effect_name)}"

    # 1. Заменяем блок констант (от "# constants from config" до пустой строки перед func)
    new_const_block = "\n".join(generate_const_block(config))

    content = re.sub(
        r"# constants from config\n(?:const .+\n?)*",
        new_const_block + "\n",
        content
    )

    # 2. Заменяем _init()
    new_init_block = "\n".join(generate_init_block(effect_name, config))

    content = re.sub(
        r"func _init\(duration : int = default_duration\) -> void:.*?(?=\nfunc |\n#|\Z)",
        new_init_block,
        content,
        flags=re.DOTALL
    )

    # 3. Заменяем get_description()
    new_get_description = "\n".join(get_description_block(effect_name, config))

    content = re.sub(
        r"func get_description\(\) -> String:.*?(?=\nfunc |\n#|\Z)",
        new_get_description,
        content,
        flags=re.DOTALL
    )

    return content


def generate_effect(effect_name: str, config: dict):
    class_name = f"StatusEffect{snake_to_pascal(effect_name)}"
    file_path = Path(OUTPUT_DIR) / f"{class_name}.gd"

    if file_path.exists():
        # Инкрементальное обновление
        content = update_existing_file(file_path, effect_name, config)
        return content, class_name, False
    else:
        # Полная генерация с нуля
        content, class_name = generate_full_file(effect_name, config)
        return content, class_name, True


# ===== МОДИФИКАЦИЯ StatusEffectGenerator.gd =====

def update_generator_file(effects_data: list[tuple[str, dict]]):
    """
    Модифицирует StatusEffectGenerator.gd:
    - Обновляет enum STATUS со всеми эффектами
    - Обновляет color_by_type с цветами для каждого эффекта
    - Обновляет create_status() с рабочим match
    """
    generator_path = Path(GENERATOR_PATH).resolve()
    if not generator_path.exists():
        print(f"Warning: Generator file not found at {generator_path}")
        return

    content = generator_path.read_text(encoding="utf-8")

    # Собираем имена эффектов в верхнем регистре
    effect_names_upper = []
    for name, _ in effects_data:
        effect_names_upper.append(snake_to_upper(name))

    # 1. Обновляем enum STATUS
    enum_lines = "\tenum STATUS {\n"
    for i, name in enumerate(effect_names_upper):
        comma = "," if i < len(effect_names_upper) - 1 else ""
        enum_lines += f"\t\t{name}{comma}\n"
    enum_lines += "\t}\n"

    content = re.sub(
        r"enum STATUS \{(?:[^}]*)\}",
        enum_lines.strip(),
        content,
        flags=re.DOTALL
    )

    # 2. Извлекаем существующие цвета из файла, чтобы сохранить их
    existing_colors = {}
    color_match = re.search(
        r"const color_by_type : Dictionary = \{(.*?)\}",
        content,
        flags=re.DOTALL
    )
    if color_match:
        for line in color_match.group(1).split("\n"):
            line = line.strip()
            m = re.match(r"STATUS\.(\w+)\s*:\s*(Color\([^)]+\))", line)
            if m:
                existing_colors[m.group(1)] = m.group(2)

    # Обновляем color_by_type, сохраняя существующие цвета
    color_lines = "\tconst color_by_type : Dictionary = {\n"
    for name, _ in effects_data:
        upper_name = snake_to_upper(name)
        if upper_name in existing_colors:
            color = existing_colors[upper_name]
        else:
            color = generate_color_from_name(name)
        color_lines += f"\t\tSTATUS.{upper_name} : {color},\n"
    color_lines += "\t}\n"

    # Находим существующий color_by_type и заменяем
    content = re.sub(
        r"const color_by_type : Dictionary = \{[^}]*\}",
        color_lines.strip(),
        content,
        flags=re.DOTALL
    )

    # 3. Обновляем create_status()
    create_status_lines = "func create_status(type : STATUS) -> StatusEffectBase:\n"
    create_status_lines += "\tvar type_str = STATUS.find_key(type)\n"
    create_status_lines += "\tmatch(type):\n"

    for name, _ in effects_data:
        upper = snake_to_upper(name)
        class_name = f"StatusEffect{snake_to_pascal(name)}"
        create_status_lines += f"\t\tSTATUS.{upper}:\n"
        create_status_lines += f"\t\t\tvar status = {class_name}.new()\n"
        create_status_lines += f"\t\t\treturn status\n"

    create_status_lines += (
        "\n\tprinterr(\"unsupported status type\")\n"
        "\treturn StatusEffectBase.new(3)\n"
    )

    # Находим существующий create_status и заменяем
    content = re.sub(
        r"func create_status\(type : STATUS\) -> StatusEffectBase:.*?(?=\nfunc |\n#|\Z)",
        create_status_lines.strip(),
        content,
        flags=re.DOTALL
    )

    generator_path.write_text(content, encoding="utf-8")
    print(f"Updated: {generator_path}")


# ===== MAIN =====

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    with open(STATS_JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    defaults = data.get("__default__", {})
    
    # Собираем данные для последующей модификации генератора
    effects_data = []

    for effect_name, config in data.items():
        # пропускаем служебные секции
        if effect_name.startswith("__"):
            continue
        
        merged_config = defaults.copy()
        merged_config.update(config)
        
        content, class_name, is_new = generate_effect(effect_name, merged_config)

        file_path = Path(OUTPUT_DIR) / f"{class_name}.gd"

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)

        if is_new:
            print(f"Generated: {file_path}")
        else:
            print(f"Updated: {file_path} (constants + _init)")
        
        effects_data.append((effect_name, merged_config))

    # Модифицируем StatusEffectGenerator.gd
    update_generator_file(effects_data)


if __name__ == "__main__":
    main()